butenko_blog_homepage:
    pattern:  /
    defaults: { _controller: ButenkoBlogBundle:Default:index }
butenko_blog_create_article:
    pattern: /create
    defaults: { _controller: ButenkoBlogBundle:Default:createArticle }
butenko_blog_show_article:
    pattern: /show/{title}
    defaults: { _controller: ButenkoBlogBundle:Default:showArticle, title: null }
butenko_blog_show_by_tags:
    pattern: /showbytags
    defaults: { _controller: ButenkoBlogBundle:Default:showByTags }

butenko_guest_book:
    pattern: /guestbook
    defaults: { _controller: ButenkoBlogBundle:GuestBook:index }
