butenko_blog_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ButenkoBlogBundle:Default:index }
butenko_blog_create:
    pattern: /create
    defaults: { _controller: ButenkoBlogBundle:Default:create }
butenko_blog_new_article:
    pattern: /new
    defaults: { _controller: ButenkoBlogBundle:Default:newArticle }
butenko_blog_show:
    pattern: /show/{title}
    defaults: { _controller: ButenkoBlogBundle:Default:show, title: null }
butenko_blog_show_by_tags:
    pattern: /showbytags
    defaults: { _controller: ButenkoBlogBundle:Default:showByTags }
