parameters:
#    butenko_blog.example.class: Butenko\BlogBundle\Example

services:
#    butenko_blog.example:
#        class: %butenko_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
