assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

    assets:
        css:
            inputs:
                - %kernel.root_dir%/../vendor/twitter/bootstrap/dist/css/bootstrap.min.css
                - %kernel.root_dir%/../vendor/twitter/bootstrap/docs/examples/blog/blog.css
            filters:
                - cssrewrite
            output: mystyle.css
        js:
            inputs:
                - %kernel.root_dir%/../components/jquery/jquery.min.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js
            output: myjs.js